---
- name: Testing AAP Project Creation
  hosts: localhost
  become: true
  tasks:

    - name: Display test message
      ansible.builtin.debug:
        msg: "This is a test from {{ ansible_facts['hostname'] }}!"
